<h1 align="center">Phát hiện Fake News với Python</h1>

### <b>Tổng quan</b>

Trong thời đại mạng xã hội ngày nay, việc đặt niềm tin vào mọi thông tin mà chúng ta nghe được trở nên khó khăn hơn bao giờ hết. Bạn có tin tưởng mọi thông tin từ mạng xã hội hay không? Liệu tất cả tin tức có đều là thật?

Tin giả, hay còn được gọi là tin rác, là những thông tin sai lệch được trình bày dưới dạng tin tức với mục đích gây hiểu lầm hoặc tổn hại danh tiếng cá nhân, tổ chức, thậm chí kiếm lợi nhuận thông qua doanh thu quảng cáo. Thuật ngữ này không chỉ giới hạn ở thông tin mạo danh mà còn bao gồm các thông tin sai lệch do vô ý hoặc vô ý thức, cũng như sự lạm dụng của những người có quyền lực.

Tin giả không chỉ ảnh hưởng đến sự cạnh tranh với tin thật mà còn làm suy giảm lòng tin của con người vào tin tức đáng tin cậy. Một số nghiên cứu đã chỉ ra rằng, tin giả thậm chí còn nhận được sự chú ý nhiều hơn so với tin thật.

Để đối mặt với quy mô lớn và sự đa dạng của tin giả, nếu chúng ta chỉ  có sự kết hợp của lý trí và kỹ năng tư duy phản biện là không đủ đưa ra kết luận, mà chúng ta còn cần các chiến lược chống lại tin giả , hiện đang được nghiên cứu tích cực, từ thuật toán sàng lọc tin tức đến sự tăng cường khả năng phát hiện thông tin sai lệch.

### <b>Giới thiệu về dự án</b>

Dự án này có mục tiêu là phát hiện tin tức giả mạo bằng cách sử dụng thư viện <code>scikit-learn (sklearn)</code>. Trong quá trình triển khai, chúng ta sẽ xây dựng một <code>TfidfVectorizer</code> trên tập dữ liệu của mình. Sau đó, sẽ khởi tạo một bộ phân loại thụ động (<code>PassiveAggressiveClassifier</code>) được điều chỉnh sao cho phù hợp với quá trình huấn luyện của mô hình. Cuối cùng, để kiểm tra tính hiệu quả của mô hình, chúng ta sẽ sử dụng <code>accuracy_score</code> (chỉ số đánh giá độ chính xác của mô hình máy học) và <code>confusion_matrix</code> (một công cụ quan trọng để đánh giá hiệu suất của mô hình phân loại, thường được sử dụng để hiển thị số lượng các dự đoán đúng và sai trong mỗi phân khúc của tập dữ liệu).

Để tiếp tục dự án này, chúng ta cần tìm hiểu sâu hơn về hai khái niệm quan trọng: <code>TfidfVectorizer</code> và <code>PassiveAggressiveClassifier</code>.

#### 1. TfidfVectorizer là gì?

<code>TfidfVectorizer</code> được sử dụng khi ta muốn chuyển đổi một tập hợp các tài liệu thô thành một ma trận các tính năng <code>TF-IDF</code>.

<code>TF: Term Frequency</code> (Tần suất xuất hiện của từ) là số lần từ xuất hiện trong văn bản. Vì các văn bản có thể có độ dài ngắn khác nhau nên một số từ có thể xuất hiện nhiều lần trong một văn bản dài hơn là một văn bản ngắn. Như vậy, <code>Term Frequency</code> thường được chia cho độ dài văn bản (Tổng số từ trong một văn bản).

$$tf(t, d) = \dfrac{f(t, d)}{\max{\{f(w, d): w \in d\}}}$$
Trong đó:
- $tf(t, d)$: Tần suất xuất hiện của từ $t$ trong văn bản $d$,
- $f(t, d)$: Số lần xuất hiện của từ $t$ trong văn bản $d$,
- $\max{\{f(w, D): w \in d\}}$: Số lần xuất hiện của từ có số lần xuất hiện nhiều nhất trong văn bản $d$.

<code>IDF: Inverse Document Frequency</code> (Tần số nghịch của 1 từ trong tập văn bản), giúp đánh giá tầm quan trọng của một từ. Khi tính toán TF, tất cả các từ được coi như có độ quan trọng bằng nhau. Nhưng một số từ như "is", "of" và "that" thường xuất hiện rất nhiều lần nhưng độ quan trọng là không cao. Như thế chúng ta cần giảm độ quan trọng của những từ này xuống.

$$idf(t, D) = \log\dfrac{|D|}{|\{d \in D: t \in d\}|}$$
Trong đó:
- $idf(t, D)$: Giá trị $idf$ của từ $t$ trong tập văn bản $D$,
- $|D|$: Tổng số văn bản trong tập $D$,
- $|\{d \in D: t \in d\}|$: Thể hiện số văn bản trong tập $D$ có chừa từ $t$.

Cuối cùng, ta có công thức tính <code>TF-IDF</code> hoàn chỉnh như sau: $$tfidf(t, d, D) = tf(t, d) \times idf(t, D)$$
Khi đó, những từ có giá trị <code>TF-IDF</code> cao là những từ xuất hiện nhiều trong văn bản này nhưng xuất hiện ít ở các văn bản khác. Việc này giúp lọc ra những từ phổ biến và giữ lại những từ có giá trị cao (từ khoá của văn bản).

#### 2. PassiveAggressionClassifier là gì?

<code>PassiveAggressionClassifier</code> (Bộ phân loại tích cực thụ động) thuộc loại thuật toán học trực tuyến (Online learning) trong máy học. Nó hoạt động bằng cách phản hồi thụ động đối với các phân loại chính xác và phản hồi tích cực đối với bất kỳ tính toán sai nào, do đó nó liên tục tự cập nhật và điều chỉnh.

Thuật toán này hoạt động bằng cách huấn luyện mô hình từng bước, nhận dữ liệu một cách tuần tự hoặc theo nhóm nhỏ. Trong online learning, mô hình tiếp tục học khi xuất hiện dữ liệu mới. Do đó, <code>PassiveAggressionClassifier</code> là lựa chọn tốt cho hệ thống nhận dữ liệu liên tục.

### <b>Tập dữ liệu</b>
Tập dữ liệu được sử dụng trong mô hình có tên là <code>news.csv</code> (nguồn: <code>train.csv</code> từ <a href="https://www.kaggle.com/c/fake-news/data">Kaggle</a> nhưng có thêm bớt vài nghìn bài báo). Trong đó có các đề mục là:
- id: mã định danh duy nhất cho mỗi bài báo
- title: tiêu đề của bài báo
- author: tác giả của bài báo
- text: nội dung của bài báo, có thể không đầy đủ
- label: một nhãn để đánh dấu bài báo có thể không đáng tin cậy
    - 1: không đáng tin cậy - tin chưa chuẩn - FAKE
    - 0: đáng tin cậy - tin chuẩn - REAL

### <b>Xây dựng mô hình</b>

#### 1. Import các thư viện cần thiết

Các thư viện bao gồm numpy, pandas và sklearn.
Do tập dữ liệu đầu vào của chúng ta là dạng văn bản(text) cho nên chúng ta cần phải đưa về một dạng dữ diệu có thể sử dụng được trong quan điểm của Machine Learing. Ở đây, chúng ta sẽ sử dụng cách véc tơ hóa để biến đổi dữ liệu từ text thành mảng hoặc một dạng dữ liệu tương đương với véc tơ.

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

#### 2. Đọc dữ liệu vào DataFrame

Ở bước kế tiếp sau khi đã có được các thư viện cần thiết. Chúng ta sẽ bắt đầu làm việc với nó, đầu tiên là thực hiện các lệnh đọc và in ra dữ liệu theo cách dưới đây:

In [2]:
# Đọc dữ liệu vào dataframe
df = pd.read_csv("./news.csv")
# Xem kích thước và 5 dòng đầu của dữ liệu
print("Shape:", df.shape)
df.head(5)

Shape: (21250, 5)

,id,title,author,text,label
0,0,"After F.B.I.’s Inquiry Into Omar Mateen, a Foc...",Matt Apuzzo and Eric Lichtblau,"WASHINGTON — Every day, in F. B. I. offices...",0
1,1,George Mason Univ. Gets Their Fascism On – Who...,Terresa Monroe-Hamilton,George Mason Univ. Gets Their Fascism On – W...,1
2,2,Milo: Free Speech Is ’Under Threat’ on College...,Trent Baker,Following the violent protest at earlier thi...,0
3,3,JUDGMENT DAY: The One Reason Why Every Christi...,Geoffrey Grider,JUDGMENT DAY: The One Reason Why Every Chris...,1
4,4,Harry Reid Just Accused FBI Of Hiding “Explosi...,Grant Stern,Comments \nDemocratic Senate leader Harry Reid...,1

Dữ liệu của chúng ta sẽ bao gồm id, tiêu đề(title), tác giả(author), nội dung(text), và nhãn đánh dấu fake hoặc real (label).
Trong đó nhãn đánh đấu của chúng ta sẽ bao gồm 0 và 1 với nhãn 0 là tin chuẩn (real) và nhãn 1 là tin chưa chuẩn (fake).

In [3]:
# Xem thông tin của tập các tin giả và tin thật
fake = df[df["label"] == 1].count()
real = df[df["label"] == 0].count()
df_counts = {
    "": ["FAKE", "REAL"],
    "Total news": [fake["id"], real["id"]],
    "Total titles": [fake["title"], real["title"]],
    "Total authors": [fake["author"], real["author"]],
    "Total texts": [fake["text"], real["text"]],
}
pd.DataFrame(df_counts)

         Total news  Total titles  Total authors  Total texts
0  FAKE       10413          9855           8482        10374
1  REAL       10837         10837          10570        10837

#### 3. Thay đổi và lấy các nhãn của DataFrame

Các tính năng cần quan tâm của chúng ta sẽ là nhãn và các văn bản. Các cột văn bản chứa nội dung bao gồm tiêu đề, tác giả và nội dung bài viết. Cột nhãn sẽ được thay đổi từ nhị phân thành văn bản là FAKE và REAL tương ứng lần lượt với 1 và 0

Nếu như chúng ta để nguyên label là 0 hoặc 1 thì có thể người sử dụng sẽ không phân biệt được đâu là REAL hoặc FAKE vì các họ không biết 0 và 1 cái nào là REAL cái nào là FAKE. Nếu giữ 0 và 1 làm output thì phải chú thích cho người dùng hiểu được thông qua một cách nhắc nhở nào đó, điều này rất bất tiện. Do đó, việc thay đổi label là cần thiết.

In [4]:
# Thay đổi các nhãn của dataframe
df["label"] = df["label"].astype("object")
df.loc[(df["label"] == 1), ["label"]] = "FAKE"
df.loc[(df["label"] == 0), ["label"]] = "REAL"

In [5]:
# Xem lại 5 dòng đầu của dữ liệu
df.head(5)

,id,title,author,text,label
0,0,"After F.B.I.’s Inquiry Into Omar Mateen, a Foc...",Matt Apuzzo and Eric Lichtblau,"WASHINGTON — Every day, in F. B. I. offices...",REAL
1,1,George Mason Univ. Gets Their Fascism On – Who...,Terresa Monroe-Hamilton,George Mason Univ. Gets Their Fascism On – W...,FAKE
2,2,Milo: Free Speech Is ’Under Threat’ on College...,Trent Baker,Following the violent protest at earlier thi...,REAL
3,3,JUDGMENT DAY: The One Reason Why Every Christi...,Geoffrey Grider,JUDGMENT DAY: The One Reason Why Every Chris...,FAKE
4,4,Harry Reid Just Accused FBI Of Hiding “Explosi...,Grant Stern,Comments \nDemocratic Senate leader Harry Reid...,FAKE

Ta có thể thấy, label đã được thay đổi output thành REAL hoặc FAKE thuận tiện hơn trong việc sử dụng

Nếu như chỉ muốn xem tin chuẩn hay không chuẩn mà không quan tâm đến nội dung hay tác giả, ta có thể thực hiện như sau:

In [6]:
# Lấy các nhãn từ dataframe
labels = df.label
labels.head(5)

0    REAL
1    FAKE
2    REAL
3    FAKE
4    FAKE
Name: label, dtype: object

#### 4. Chia bộ dữ liệu thành các tập train và test

In [7]:
# Trộn tiêu đề, tác giả và nội dung
df["combined_info"] = df.apply(
    lambda row: f"Title: {row['title']}\nAuthors: {row['author']}\nText:\n{row['text']}",
    axis=1,
)

# Chia bộ dữ liệu
x_train, x_test, y_train, y_test = train_test_split(
    df["combined_info"], labels, test_size=0.2, random_state=7
)

#### 5. Khởi tạo TfidfVectorizer và thực hiện fit, transform

In [8]:
# Khởi tạo TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words="english", max_df=0.7)

# Fit and transform train set, transform test set
tfidf_train = tfidf_vectorizer.fit_transform(x_train)
tfidf_test = tfidf_vectorizer.transform(x_test)

#### 6. Khởi tạo PassiveAggressionClassifier và thực hiện dự đoán

In [9]:
# Khởi tạo PassiveAggressiveClassifier
pac = PassiveAggressiveClassifier(max_iter=50)
pac.fit(tfidf_train, y_train)

# Dự đoán trên tập test và tính toán độ chính xác
y_pred = pac.predict(tfidf_test)
score = accuracy_score(y_test, y_pred)
print(f"Accuracy: {round(score*100,2)}%")

Accuracy: 95.98%

#### 7. In ra ma trận hỗn loạn

In [10]:
# Xây dựng ma trận hỗn loạn
cm = confusion_matrix(y_test, y_pred, labels=["FAKE", "REAL"])
cm_df = pd.DataFrame(
    cm, index=["True_FAKE", "True_REAL"], columns=["Pred_FAKE", "Pred_REAL"]
)
cm_df

           Pred_FAKE  Pred_REAL
True_FAKE       1972         99
True_REAL         72       2107

#### 8. Thực hiện dự đoán với nội dung được nhập vào

In [14]:
from newspaper import Article

url = input("Nhập url của bài báo")
article = Article(url)
article.download()
article.parse()

text_input = f"Title: {article.title}\nAuthors: {', '.join(article.authors)}\nText:\n{article.text}"

text_tfidf = tfidf_vectorizer.transform([text_input])
label_pred = pac.predict(text_tfidf)
print(f"Kết quả dự đoán: {label_pred}")

print(" ".join(text_input.split(" ")[:100]) + " ...")

Kết quả dự đoán: ['REAL']
Title: Vietnamese rice ST25 named world's best rice 2023
Authors: Thuy Duong, en.baochinhphu.vn
Text:
Illustrative image

This is the second time the ST25 rice variety has seized the award. This year's competition saw the participation of more than ten countries with 30 rice samples. The second prize went to Cambodian rice, while the third-place award went to Indian rice.

ST25 (Gao Ong Cua in Vietnamese) rice results from 20 years of research by the Hero of Labor, Ho Quang Cua.

ST25 variety is the latest generation of the famous fragrant rice line with many qualities considered "premium". From seed selection to planting, all comply with the ...