<h1 align="center">Phát hiện Fake News với Python</h1>

Trong thời đại bùng nổ thông tin và sự phát triển nhanh chóng của các mạng xã hội, việc đối mặt với đợt sóng "Fake News" - hay tin đồn giả mạo, đang trở thành một thách thức ngày càng lớn đối với sự minh bạch và đáng tin cậy của thông tin. Điều này không chỉ đặt ra thách thức về quản lý thông tin mà còn đe dọa đến sự ổn định của nền kinh tế tri thức và tự do ngôn luận. Trong bối cảnh này, việc phát triển một mô hình nhằm cải thiện khả năng lọc thông tin chính xác đóng vai trò hết sức quan trọng trong việc ngăn chặn thông tin giả mạo. Vậy có cách nào để làm được việc đấy không? Câu trả lời là có. Sau đây, chúng tôi sẽ giới đến mọi người mô hình <b>"Phát hiện Fake News với Python".</b>

### <b>Tập dữ liệu</b>
Tập dữ liệu được sử dụng trong mô hình có tên là <code>news.csv</code> (nguồn: <code>train.csv</code> của <a href="https://www.kaggle.com/c/fake-news/data">Kaggle</a>), trong đó có các đề mục là:
- id: mã định danh duy nhất cho mỗi bài báo
- title: tiêu đề của bài báo
- author: tác giả của bài báo
- text: nội dung của bài báo, có thể không đầy đủ
- label: một nhãn để đánh dấu bài báo có thể không đáng tin cậy
    - 1: không đáng tin cậy - tin chưa chuẩn - FAKE
    - 0: đáng tin cậy - tin chuẩn - REAL

### <b>Xây dựng mô hình</b>

#### 1. Import các thư viện cần thiết

In [28]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

#### 2. Đọc dữ liệu vào DataFrame

In [29]:
# Đọc dữ liệu vào dataframe
df = pd.read_csv("./news.csv")
# Xem kích thước và 5 dòng đầu của dữ liệu
print("Shape:", df.shape)
df.head(5)

Shape: (20800, 5)

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [30]:
# Xem 5 dòng đầu của dữ liệu không có nội dung
df_na = df[df["text"].isna()].head(5)
df_na

,id,title,author,text,label
142,142,Gorafi Magazine : Entretien exclusif avec Bara...,NaN,NaN,1
573,573,Le top des recherches Google passe en top des ...,NaN,NaN,1
1200,1200,La Corée du Nord annonce avoir envoyé un missi...,NaN,NaN,1
1911,1911,Grand-Prix du Brésil – Romain Grosjean obtient...,NaN,NaN,1
2148,2148,Gorafi Magazine: Barack Obama « Je vous ai déj...,NaN,NaN,1

In [31]:
# Xử lý nội dung từ NaN thành chuỗi rỗng
df["text"] = df["text"].replace({np.nan: ""})
df.loc[list(df_na["id"])]

,id,title,author,text,label
142,142,Gorafi Magazine : Entretien exclusif avec Bara...,NaN,,1
573,573,Le top des recherches Google passe en top des ...,NaN,,1
1200,1200,La Corée du Nord annonce avoir envoyé un missi...,NaN,,1
1911,1911,Grand-Prix du Brésil – Romain Grosjean obtient...,NaN,,1
2148,2148,Gorafi Magazine: Barack Obama « Je vous ai déj...,NaN,,1

#### 3. Thay đổi và lấy các nhãn của DataFrame

In [32]:
# Thay đổi các nhãn của dataframe
df["label"] = df["label"].astype("object")
df.loc[(df["label"] == 1), ["label"]] = "FAKE"
df.loc[(df["label"] == 0), ["label"]] = "REAL"

# Lấy các nhãn từ dataframe
labels = df.label
labels.head(5)

0    FAKE
1    REAL
2    FAKE
3    FAKE
4    FAKE
Name: label, dtype: object

#### 4. Chia bộ dữ liệu thành các tập train và test

In [33]:
x_train, x_test, y_train, y_test = train_test_split(
    df["text"], labels, test_size=0.2, random_state=7
)

#### 5. Khởi tạo TfidfVectorizer và thực hiện các điều chỉnh, biến đổi

In [34]:
# Khởi tạo TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words="english", max_df=0.7)

# Fit and transform train set, transform test set
tfidf_train = tfidf_vectorizer.fit_transform(x_train)
tfidf_test = tfidf_vectorizer.transform(x_test)

#### 6. Khởi tạo PassiveAggressionClassifier và thực hiện dự đoán

In [35]:
# Khởi tạo PassiveAggressiveClassifier
pac = PassiveAggressiveClassifier(max_iter=50)
pac.fit(tfidf_train, y_train)

# Dự đoán trên tập test và tính toán độ chính xác
y_pred = pac.predict(tfidf_test)
score = accuracy_score(y_test, y_pred)
print(f"Accuracy: {round(score*100,2)}%")

Accuracy: 96.61%

#### 7. In ra ma trận hỗn loạn

In [36]:
# Build confusion matrix
cm = confusion_matrix(y_test, y_pred, labels=["FAKE", "REAL"])
df_cm = pd.DataFrame(cm, index=['True_FAKE', 'True_REAL'], columns=['Pred_FAKE', 'Pred_REAL'])
df_cm

           Pred_FAKE  Pred_REAL
True_FAKE       2033         67
True_REAL         74       1986